#!/bin/sh

set -e
set -x

breakpoint_addr () {
  grep breakpoint ./build/isaac.sym | awk '{ print $3 }'
}

breakpoint=$(breakpoint_addr)
if [ "$breakpoint" == "" ]; then
  fuse ./build/isaac.sna
else
  fuse ./build/isaac.sna --debugger-command="break $(breakpoint_addr)"
fi
