t_wall_corner_ul:
        dg XXXXXXXX-XXXXXXX
        dg XXXXXXXX-XXXXXXX
        dg X-X-X-X-X-------
        dg -XXXXX--X-------
        dg X-X-X-X-X-------
        dg ---XXXXX-XX-----
        dg --X-X-X-XX-X-X--
        dg -----XXXXXXXXXXX
        dg ----X-XXX-X----X
        dg -------XXXXX---X
        dg ------X-X-X-X---
        dg ---------XXXXX--
        dg --------X-X-XXXX
        dg -----------XXXXX
        dg ----------X-X-X-
        dg -------------XXX
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.off)

t_wall_corner_ur:
        dg XXXXXXX-XXXXXXXX
        dg XXXXXXX-XXXXXXXX
        dg -------X-X-X-X-X
        dg -------X--XXXXX-
        dg -------X-X-X-X-X
        dg -----XX-XXXXX---
        dg --X-X-XX-X-X-X--
        dg XXXXXXXXXXX-----
        dg X----X-XXX-X----
        dg X---XXXXX-------
        dg ---X-X-X-X------
        dg --XXXXX---------
        dg XXXX-X-X--------
        dg XXXXX-----------
        dg -X-X-X----------
        dg XXX-------------
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.off)
        db (Color.white + Bg.red + Bright.on)

t_wall_corner_dl:
        dg -------------XXX
        dg ----------X-X-X-
        dg -----------XXXXX
        dg --------X-X-XXXX
        dg ---------XXXXX--
        dg ------X-X-X-X---
        dg -------XXXXX---X
        dg ----X-XXX-X----X
        dg -----XXXXXXXXXXX
        dg --X-X-X-XX-X-X--
        dg ---XXXXX-XX-----
        dg X-X-X-X-X-------
        dg -XXXXX--X-------
        dg X-X-X-X-X-------
        dg XXXXXXXX-XXXXXXX
        dg XXXXXXXX-XXXXXXX
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.off)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)

t_wall_corner_dr:
        dg XXX-------------
        dg -X-X-X----------
        dg XXXXX-----------
        dg XXXX-X-X--------
        dg --XXXXX---------
        dg ---X-X-X-X------
        dg X---XXXXX-------
        dg X----X-XXX-X----
        dg XXXXXXXXXXX-----
        dg --X-X-XX-X-X-X--
        dg -----XX-XXXXX---
        dg -------X-X-X-X-X
        dg -------X--XXXXX-
        dg -------X-X-X-X-X
        dg XXXXXXX-XXXXXXXX
        dg XXXXXXX-XXXXXXXX
        db (Color.white + Bg.red + Bright.off)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)
        db (Color.white + Bg.red + Bright.on)